version: '3.8'

services:
  db_dev:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: portdata
      MYSQL_USER: example
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: